version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQA_0702Project
  gitServerName: SIQA_KVV_IBM
  gitUrl: https://github.com/Karthik-V-IBM-10
  gitUsername: Karthik-V-IBM-10
  gitBranch: main
- name: WmJDBCAdapter
  version: 10.3.0.0.34
  wpmServer: https://packages.webmethods.io
  wpmRegistry: licensed
- name: SIQAJDBCAdapterTests
  gitServerName: SIQA_kvv_wm_io
  gitUrl: https://github.webmethods.io/mjan
  gitUsername: kvv
  gitBranch: main
- name: DADA_GlobalVariable1
  gitServerName: SIQA_kvv_wm_io
  gitUrl: https://github.webmethods.io/mjan
  gitUsername: kvv
  gitBranch: main
services:
- serviceName: project.siqa_0702.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections:Database_702
  packages:
  - name: SIQA_0702Project
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: project.siqa_0702.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.operations.actions:DBInsert
  packages:
  - name: SIQA_0702Project
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: project.siqa_0702.integrations:AlertsCRTandERT
  packages:
  - name: SIQA_0702Project
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: pub.alert:emit
  packages:
  - name: WmPublic
    version: 11.1.0.0.2033
- serviceName: project.siqa_0702.integrations:SIQAAdapterFlow
  packages:
  - name: SIQA_0702Project
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: project.siqa_0702.integrations:Sum
  packages:
  - name: SIQA_0702Project
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: pub.math:addInts
  packages:
  - name: WmPublic
    version: 11.1.0.0.2033
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 11.1.0.0.2033
- serviceName: project.siqa_0702.integrations:deepclonetest
  packages:
  - name: SIQA_0702Project
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: pub.string:stringToBytes
  packages:
  - name: WmPublic
    version: 11.1.0.0.2033
- serviceName: pub.utils:deepClone
  packages:
  - name: WmPublic
    version: 11.1.0.0.2033
- serviceName: pub.string:bytesToString
  packages:
  - name: WmPublic
    version: 11.1.0.0.2033
configurationVariables:
  jdbc.jdbcTestPool.waitingThread: "0"
  jdbc.jdbcTestPool.minConns: "0"
  ? artConnection.SIQA_0702Project.project.siqa_0702.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_702.connectionSettings.keyStore
  : ""
  jdbc.jdbcTestPool.expireTime: "60000"
  ? artConnection.SIQA_0702Project.project.siqa_0702.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_702.connectionSettings.user
  : sa
  ? artConnection.SIQA_0702Project.project.siqa_0702.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_702.connectionManagerSettings.startupBackoffSecs
  : "10"
  ? artConnection.SIQA_0702Project.project.siqa_0702.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_702.connectionManagerSettings.expireTimeout
  : "1000"
  ? artConnection.SIQA_0702Project.project.siqa_0702.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_702.connectionSettings.serverName
  : vmiboint01
  ? artConnection.SIQA_0702Project.project.siqa_0702.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_702.connectionManagerSettings.minimumPoolSize
  : "1"
  jdbc.jdbcTestPool.snoopparms: ddtdbg.ProtocolTraceEnable=true;ddtdbg.ProtocolTraceMaxline=16;ddtdbg.ProtocolTraceLocation=logs/snoop/jdbcTestPool.log;ddtdbg.ProtocolTraceShowTime=true
  ? artConnection.SIQA_0702Project.project.siqa_0702.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_702.connectionSettings.trustStore
  : ""
  ? artConnection.SIQA_0702Project.project.siqa_0702.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_702.connectionSettings.otherProperties
  : loginTimeout=60;driverType=thin;
  jdbc.jdbcTestPool.maxConns: "10"
  jdbc.jdbcTestPool.userid: root
  ? artConnection.SIQA_0702Project.project.siqa_0702.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_702.connectionSettings.password
  : "{AES}B2Xqma4Ost5nVUiXctJydQ=="
  ? artConnection.SIQA_0702Project.project.siqa_0702.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_702.connectionManagerSettings.heartBeatInterval
  : "0"
  jdbc.jdbcTestPool.driverAlias: MySQL Database Java Connector Driver
  ? artConnection.SIQA_0702Project.project.siqa_0702.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_702.connectionSettings.driverType
  : Progress® DataDirect®
  ? artConnection.SIQA_0702Project.project.siqa_0702.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_702.connectionSettings.dbType
  : MSSQL
  ? artConnection.SIQA_0702Project.project.siqa_0702.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_702.connectionManagerSettings.startupRetryCount
  : "0"
  jdbc.jdbcTestPool.spyenabled: "false"
  ? artConnection.SIQA_0702Project.project.siqa_0702.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_702.connectionSettings.databaseName
  : SIQACloud
  ? artConnection.SIQA_0702Project.project.siqa_0702.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_702.connectionManagerSettings.blockingTimeout
  : "1000"
  jdbc.jdbcTestPool.snoopenabled: "false"
  ? artConnection.SIQA_0702Project.project.siqa_0702.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_702.connectionManagerSettings.maximumPoolSize
  : "10"
  jdbc.jdbcTestPool.password: "{AES}er+I3U8nDVm8F4DBRST1+A=="
  jdbc.jdbcTestPool.spyparms: SpyAttributes=(log=(file)logs/spy/jdbcTestPool.log;logTName=yes;timestamp=yes)
  jdbc.jdbcTestPool.dbURL: jdbc:mysql://mysql.test.local:3306/webm
  jdbc.jdbcTestPool.poolThreshold: "0"
  ? artConnection.SIQA_0702Project.project.siqa_0702.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_702.connectionEnabled
  : "false"
  ? artConnection.SIQA_0702Project.project.siqa_0702.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_702.connectionSettings.datasourceClass
  : com.wm.dd.jdbcx.sqlserver.SQLServerDataSource
  ? artConnection.SIQA_0702Project.project.siqa_0702.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_702.connectionSettings.portNumber
  : "1433"
  ? artConnection.SIQA_0702Project.project.siqa_0702.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_702.connectionManagerSettings.poolable
  : "false"
  ? artConnection.SIQA_0702Project.project.siqa_0702.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_702.connectionSettings.transactionType
  : NO_TRANSACTION
  ? artConnection.SIQA_0702Project.project.siqa_0702.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_702.connectionManagerSettings.poolIncrementSize
  : "1"
  jdbc.jdbcTestPool.useSSL: "false"
  ? artConnection.SIQA_0702Project.project.siqa_0702.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_702.connectionSettings.networkProtocol
  : tcp
